-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOMS/36wS8+++gXj1
idKu0FSpwKz6nWntXWbcUZtXAyygCgYIKoZIzj0DAQehRANCAATwLmxLAJ9H9ZHe
T+DlvCSqPf4znGXX1TmejlwbonkXIA0006sgb4nkzGHjwV5QhpoETzmcxpKNbWIE
2SyMmZIp
-----END PRIVATE KEY-----