[database]
kind = "MySql"
dsn = "mysql:dbname=LAA1147379-sio;host=mysql328.phy.lolipop.lan;charset=utf8mb4;"
host = "mysql328.phy.lolipop.lan"
dbname = "LAA1147379-sio"
user = "LAA1147379"
password = "Buriburi1030"

[log]
path = "/home/users/0/babyblue.jp-bouzer/web/release/siowadou_pro/log/debug_log.txt"

[profile]
path = "/home/users/0/babyblue.jp-bouzer/web/release/siowadou_pro/user_images/"

[web]
;*** サイトのURL
url = "https://www.bouzer.jp/siowadou_pro/index.html"

[screen]
;*** 一覧の行数
list_row_count = 10

[auth]
refresh_inactivity_days = 60

;[policy]
;version = "2025.11.4"
;tos_url = "https://www.bouzer.jp/hou_no_mikata/terms_of_use.html"
;privacy_url = "https://www.bouzer.jp/hou_no_mikata/privacy_policy.html"
;require_reconsent = 1

[mail]
; ローカル環境
;smtp_server = "ssl://smtp.lolipop.jp"
smtp_server = "smtp.lolipop.jp"
port_no = 465
;port_no = 587
from_mail_addr = "contact@bouzer.jp"
from_mail_addr_name = "海釣りJAPAN"
smtp_auth_user = "contact@bouzer.jp"
smtp_auth_password = "Buriburi1030_"
subject = "[海釣りJAPAN] アカウント認証コードのお知らせ"

mail_body[] = "認証コード: $authenticationNumber$"
mail_body[] = ""
mail_body[] = "上記の認証コードをご入力いただき、アカウントの認証を完了してください。"
mail_body[] = ""
mail_body[] = "※この認証コードは3分間有効です。"
mail_body[] = "※もし、アカウントの作成をお心当たりのない場合は、本メールを破棄していただきますようお願いいたします。"
mail_body[] = ""
mail_body[] = "[運営会社:Bouzer／サポート窓口情報]"
mail_body[] = ""
